### ISSUE TITLE
Portable ruby found, but glibc seems to be missing

### ISSUE THREAD

**Issue by Lyken17** [homebrew-ppc64le/homebrew-portable-ruby#1]
Hi Trung,

Thanks for sharing your scripts. This may not be the correct repo to raise issues, but the `install` repo does not enable the issue function. So I put some my updates here

After running the install scripts, I got the following msg

```bash
(base) [ligeng@service0001 ~]$ brew doctor
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
==> Downloading https://github.com/homebrew-ppc64le/homebrew-portable-ruby/releases/download/v0.1/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Error: Failed to vendor ruby 2.6.6.
Error: Failed to install vendor Ruby.
```
It shows that https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz is not available, as can be checked in https://linuxbrew.bintray.com/bottles-portable-ruby.

**Comment by runlevel5** [comment]
@Lyken17 ~I have not yet setup the bintray hosting. However the fallback GitHub URL should work.~ I have setup bintray hosting. Both should work now.

Could you please provide me the details of `HOMEBREW_VERBOSE=1 brew doctor`? And what is your Linux distro?

**Comment by Lyken17** [comment]
@runlevel5 I saw your email. Sorry for being late. I was working on a rebuttal recently. 

I force homebrew to use locally compiled ruby by setting
```bash
export HOMEBREW_FORCE_VENDOR_RUBY=$(which ruby)
export HOMEBREW_RUBY_PATH=$(which ruby)
```

```bash
(base) [ligeng@service0001 ~]$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [powerpc64le-linux]
(base) [ligeng@service0001 ~]$ which ruby
~/.local/bin/ruby
(base) [ligeng@service0001 ~]$ brew
Error: Cannot find a vendored version of ruby for your ppc64le
processor on Linuxbrew!
Error: Failed to install vendor Ruby.
```

**Comment by Lyken17** [comment]
When I try your latest scripts and type `brew doctor`

```bash
[ligeng@service0001]~% brew doctor
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://dl.bintray.com/homebrew-ppc64le/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
tar: portable-ruby/2.6.6/lib/libruby-static.a: Cannot write: Disk quota exceeded
tar: portable-ruby/2.6.6/lib/ruby/gems/2.6.0/gems/power_assert-1.1.3/lib/power_assert/context.rb: Cannot write: Disk quota exceeded
tar: portable-ruby/2.6.6/lib/ruby/gems/2.6.0/gems/power_assert-1.1.3/lib/power_assert/parser.rb: Cannot write: Disk quota exceeded
............
```

It shows `Disk quota exceeded`. Does it try to pour to some directory other than user's home?

**Comment by runlevel5** [comment]
@Lyken17 the homebrew comes with its own vendored ruby (which is portable-ruby/2.6.6) so you do not have to set `HOMEBREW_FORCE_VENDOR_RUBY` and `HOMEBREW_RUBY_PATH`.

Could you please unset those 2 UNIX environment variables then run `HOMEBREW_VERBOSE=1 brew doctor` and let me know if the portable-ruby is correctly downloaded? 

And regarding `Disk quota exceeded`, I could not tell what caused that with your provided backtraces. Could you please tell me the `uname -ar`?

Lastly, did you follow the instructions in https://github.com/homebrew-ppc64le/install?

**Comment by Lyken17** [comment]
`Disk quota`  is caused by my settings. I already solved that.

Here is the full installation log

```bash
(base) [ligeng@service0001 ~]$ export HOMEBREW_DEVELOPER=1
(base) [ligeng@service0001 ~]$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/homebrew-ppc64le/install/master/install.sh)"
==> This script will install:
/home/ligeng/.linuxbrew/bin/brew
/home/ligeng/.linuxbrew/share/doc/homebrew
/home/ligeng/.linuxbrew/share/man/man1/brew.1
/home/ligeng/.linuxbrew/share/zsh/site-functions/_brew
/home/ligeng/.linuxbrew/etc/bash_completion.d/brew
/home/ligeng/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/ligeng/.linuxbrew/bin
/home/ligeng/.linuxbrew/etc
/home/ligeng/.linuxbrew/include
/home/ligeng/.linuxbrew/lib
/home/ligeng/.linuxbrew/sbin
/home/ligeng/.linuxbrew/share
/home/ligeng/.linuxbrew/var
/home/ligeng/.linuxbrew/opt
/home/ligeng/.linuxbrew/share/zsh
/home/ligeng/.linuxbrew/share/zsh/site-functions
/home/ligeng/.linuxbrew/var/homebrew
/home/ligeng/.linuxbrew/var/homebrew/linked
/home/ligeng/.linuxbrew/Cellar
/home/ligeng/.linuxbrew/Caskroom
/home/ligeng/.linuxbrew/Homebrew
/home/ligeng/.linuxbrew/Frameworks

Press RETURN to continue or any other key to abort
==> /bin/mkdir -p /home/ligeng/.linuxbrew
==> /bin/chown ligeng:ligeng /home/ligeng/.linuxbrew
==> /bin/mkdir -p /home/ligeng/.linuxbrew/bin /home/ligeng/.linuxbrew/etc /home/ligeng/.linuxbrew/include /home/ligeng/.linuxbrew/lib /home/ligeng/.linuxbrew/sbin /home/ligeng/.linuxbrew/share /home/ligeng/.linuxbrew/var /home/ligeng/.linuxbrew/opt /home/ligeng/.linuxbrew/share/zsh /home/ligeng/.linuxbrew/share/zsh/site-functions /home/ligeng/.linuxbrew/var/homebrew /home/ligeng/.linuxbrew/var/homebrew/linked /home/ligeng/.linuxbrew/Cellar /home/ligeng/.linuxbrew/Caskroom /home/ligeng/.linuxbrew/Homebrew /home/ligeng/.linuxbrew/Frameworks
==> /bin/chmod g+rwx /home/ligeng/.linuxbrew/bin /home/ligeng/.linuxbrew/etc /home/ligeng/.linuxbrew/include /home/ligeng/.linuxbrew/lib /home/ligeng/.linuxbrew/sbin /home/ligeng/.linuxbrew/share /home/ligeng/.linuxbrew/var /home/ligeng/.linuxbrew/opt /home/ligeng/.linuxbrew/share/zsh /home/ligeng/.linuxbrew/share/zsh/site-functions /home/ligeng/.linuxbrew/var/homebrew /home/ligeng/.linuxbrew/var/homebrew/linked /home/ligeng/.linuxbrew/Cellar /home/ligeng/.linuxbrew/Caskroom /home/ligeng/.linuxbrew/Homebrew /home/ligeng/.linuxbrew/Frameworks
==> /bin/chown ligeng /home/ligeng/.linuxbrew/bin /home/ligeng/.linuxbrew/etc /home/ligeng/.linuxbrew/include /home/ligeng/.linuxbrew/lib /home/ligeng/.linuxbrew/sbin /home/ligeng/.linuxbrew/share /home/ligeng/.linuxbrew/var /home/ligeng/.linuxbrew/opt /home/ligeng/.linuxbrew/share/zsh /home/ligeng/.linuxbrew/share/zsh/site-functions /home/ligeng/.linuxbrew/var/homebrew /home/ligeng/.linuxbrew/var/homebrew/linked /home/ligeng/.linuxbrew/Cellar /home/ligeng/.linuxbrew/Caskroom /home/ligeng/.linuxbrew/Homebrew /home/ligeng/.linuxbrew/Frameworks
==> /bin/chgrp ligeng /home/ligeng/.linuxbrew/bin /home/ligeng/.linuxbrew/etc /home/ligeng/.linuxbrew/include /home/ligeng/.linuxbrew/lib /home/ligeng/.linuxbrew/sbin /home/ligeng/.linuxbrew/share /home/ligeng/.linuxbrew/var /home/ligeng/.linuxbrew/opt /home/ligeng/.linuxbrew/share/zsh /home/ligeng/.linuxbrew/share/zsh/site-functions /home/ligeng/.linuxbrew/var/homebrew /home/ligeng/.linuxbrew/var/homebrew/linked /home/ligeng/.linuxbrew/Cellar /home/ligeng/.linuxbrew/Caskroom /home/ligeng/.linuxbrew/Homebrew /home/ligeng/.linuxbrew/Frameworks
==> Downloading and installing Homebrew...
remote: Enumerating objects: 2036, done.
remote: Counting objects: 100% (2036/2036), done.
remote: Compressing objects: 100% (1730/1730), done.
remote: Total 2036 (delta 237), reused 2013 (delta 219), pack-reused 0
Receiving objects: 100% (2036/2036), 1.97 MiB | 0 bytes/s, done.
Resolving deltas: 100% (237/237), done.
From https://github.com/homebrew-ppc64le/brew
 * [new branch]      master     -> origin/master
HEAD is now at 85661b0 s/ppc/ppc64le
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://dl.bintray.com/homebrew-ppc64le/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Error: Failed to vendor ruby 2.6.6.
Error: Failed to install vendor Ruby.
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://dl.bintray.com/homebrew-ppc64le/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Error: Failed to vendor ruby 2.6.6.
Error: Failed to install vendor Ruby.
Failed during: /home/ligeng/.linuxbrew/bin/brew update --force
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (or will be during this `install` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run `brew help` to get started
- Further documentation:
    https://docs.brew.sh
- Install the Homebrew dependencies if you have sudo access:
  Debian, Ubuntu, etc.
    sudo apt-get install build-essential
  Fedora, Red Hat, CentOS, etc.
    sudo yum groupinstall 'Development Tools'
  See https://docs.brew.sh/linux for more information.
- Configure Homebrew in your /home/ligeng/.bash_profile by running
    echo 'eval $(/home/ligeng/.linuxbrew/bin/brew shellenv)' >> /home/ligeng/.bash_profile
- Add Homebrew to your PATH
    eval $(/home/ligeng/.linuxbrew/bin/brew shellenv)
- We recommend that you install GCC by running:
    brew install gcc
```

After that 

```bash
(base) [ligeng@service0001 ~]$ brew
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://dl.bintray.com/homebrew-ppc64le/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Error: Failed to vendor ruby 2.6.6.
Error: Failed to install vendor Ruby.
```

And the log for `HOMEBREW_VERBOSE=1 brew doctor`

```bash
(base) [ligeng@service0001 ~]$ HOMEBREW_VERBOSE=1 brew doctor > log.txt
/usr/bin/ruby: warning: unknown argument for --enable: `frozen-string-literal'
/usr/bin/ruby: warning: unknown argument for --disable: `did_you_mean'
-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.0.0"> (NoMethodError)
==> Downloading https://dl.bintray.com/homebrew-ppc64le/bottles-portable-ruby/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.6.ppc64le_glibc_2.17_linux.bottle.tar.gz
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/compact_index_client/
......
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/compact_index_client/updater.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/compact_index_client/cache.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/remote_specification.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/resolver/
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/resolver/spec_group.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/compact_index.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/dependency.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/index.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/downloader.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/fetcher/base.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/similarity_detector.rb
portable-ruby/2.6.6/lib/ruby/2.6.0/bundler/environment_preserver.rb
............
Error: Failed to vendor ruby 2.6.6.
Error: Failed to install vendor Ruby.
```

**Comment by Lyken17** [comment]
It seems that `export HOMEBREW_FORCE_VENDOR_RUBY=$(which ruby)` and `export HOMEBREW_RUBY_PATH=$(which ruby)` are necessary 

```bash
(base) [ligeng@service0001 pkg-config-0.29.2]$ HOMEBREW_VERBOSE=1 brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/ligeng/anaconda3/bin/curl-config
  /home/ligeng/anaconda3/bin/xml2-config
  /home/ligeng/anaconda3/bin/icu-config
  /home/ligeng/anaconda3/bin/python3-config
  /home/ligeng/anaconda3/bin/freetype-config
  /home/ligeng/anaconda3/bin/libpng16-config
  /home/ligeng/anaconda3/bin/python3.7-config
  /home/ligeng/anaconda3/bin/xslt-config
  /home/ligeng/anaconda3/bin/krb5-config
  /home/ligeng/anaconda3/bin/pcre-config
  /home/ligeng/anaconda3/bin/python3.7m-config
  /home/ligeng/anaconda3/bin/libpng-config
  /home/ligeng/anaconda3/bin/ncursesw6-config
  /home/software/spack/netcdf-fortran/4.5.2-6ssuhsslyafzmlbvltnsuevm23fuag5o/bin/nf-config
  /bin/pkg-config
  /bin/net-snmp-config
  /bin/python-config
  /bin/python2-config
  /bin/python2.7-config
  /bin/octave-config
  /bin/ncurses5-config
  /bin/ncursesw5-config
  /bin/pcre-config
  /bin/krb5-config

Warning: You have uncommitted modifications to homebrew-ppc64le/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/ligeng/.linuxbrew/Homebrew && git stash && git clean -d -f

Uncommitted files:
  ?? Library/Taps/homebrew/homebrew-core/

Warning: An outdated version (1.8.3.1) of Git was detected in your PATH.
Git 2.7.0 or newer is required for Homebrew.
Please upgrade:
  brew install git

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
```

Though it still has problem installing packages 

```bash
(base) [ligeng@service0001 ~]$ brew install gcc
==> Installing dependencies for curl: pkg-config, openssl@1.1 and zlib
==> Installing curl dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Last 15 lines from /home/ligeng/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... powerpc64le-unknown-linux-gnu
checking host system type... powerpc64le-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20200421-161398-rtdeh0/pkg-config-0.29.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
............
```

Looks like it has difficulty finding the compiler.

**Comment by Lyken17** [comment]
But an interesting thing is that, if I perform the `configure` manually, no error occurs during the setup.

```bash
(base) [ligeng@service0001 pkg-config-0.29.2]$ ./configure --disable-debug --prefix=/home/ligeng/.linuxbrew/Cellar/pkg-config/0.29.2_4 --disable-host-tool --with-internal-glib --with-pc-path=/home/ligeng/.linuxbrew/lib/pkgconfig:/home/ligeng/.linuxbrew/share/pkgconfig:/home/ligeng/.linuxbrew/Homebrew/Library/Homebrew/os/linux/pkgconfig --with-system-include-path=/usr/include
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... powerpc64le-unknown-linux-gnu
checking host system type... powerpc64le-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
............
```

**Comment by runlevel5** [comment]
> It seems that export HOMEBREW_FORCE_VENDOR_RUBY=$(which ruby) and export HOMEBREW_RUBY_PATH=$(which ruby) are necessary

These 2 options are only needed for falling back to the host's Ruby when there is no vendored ruby binary. We do want them unset so `brew` could use the vendored Ruby binary.

> $ HOMEBREW_VERBOSE=1 brew doctor

Those warnings are pretty okay. They aren't errors.

> $  brew install gcc

`gcc` formula is not working yet, I am fixing it. For the time-being, you could use your host OS's gcc. 

So as far as I could see, the brew works fine on your box. Those issues with gcc is more related to the formulas. Please feel free to report any formula that is not working at github.com/homebrew-ppc64le/homebrew-core

**Comment by Lyken17** [comment]
Thanks for your help. I just tested `brew install curl`, which yields following errors

```bash
(base) [ligeng@service0001 ~]$ brew install curl
==> Installing dependencies for curl: openssl@1.1 and zlib
==> Installing curl dependency: openssl@1.1
==> Downloading https://www.openssl.org/source/openssl-1.1.1f.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/downloads/cff8d99f8b301b9008a767ee378d92b5ff38ca3f6fc3dbc3c283070508ba79d2--openssl-1.1.1f.tar.gz
==> perl ./Configure --prefix=/home/ligeng/.linuxbrew/Cellar/openssl@1.1/1.1.1f --openssldir=/home/ligeng/.linuxbrew/etc/openssl@1.1 no-ssl3 no-ssl3-method no-
Updating Homebrew...
==> make
Last 15 lines from /home/ligeng/.cache/Homebrew/Logs/openssl@1.1/02.make:
    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/usr/bin/make depend && /usr/bin/make _all
make[1]: Entering directory `/tmp/openssl@1.1-20200423-92938-1vauvnu/openssl-1.1.1f'
make[1]: Leaving directory `/tmp/openssl@1.1-20200423-92938-1vauvnu/openssl-1.1.1f'
make[1]: Entering directory `/tmp/openssl@1.1-20200423-92938-1vauvnu/openssl-1.1.1f'
gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/ligeng/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/home/ligeng/.linuxbrew/Cellar/openssl@1.1/1.1.1f/lib/engines-1.1\"" -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
cc1: error: unrecognized argument in option '-mcpu=power9'
cc1: note: valid arguments to '-mcpu=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan
```

The main error is 
```bash
cc1: error: unrecognized argument in option '-mcpu=power9'
```

Seems a lot of compiler options need to be updated : |  

While I will try to see how can I fix these building scripts, I would recommend [spack](https://github.com/spack/spack) as an alternative option.

Again, appreciate for your help. It is really helpful.

**Comment by runlevel5** [comment]
@Lyken17 I thought I have fixed this issue with https://github.com/homebrew-ppc64le/homebrew-core/commit/88b2cefa746f7a5adb848c8e8be6396370e16393. Could you please run `brew update` then try again?

**Comment by runlevel5** [comment]
@Lyken17 spack's seems a good alternative however I am keen to pursue homebrew because I have been using it on macOS for many years.

There are still rough edges atm as many formulas needs adjustment to compile for ppc64le. Bear with me while I am working on setting up a proper CI so I could properly determine how many formulas that need more work.

**Comment by Lyken17** [comment]
Unfortunately, it still does not work. I think the issue is about locating CC / CXX compiler. 

```bash
(base) [ligeng@service0001 ~]$ brew update --verbose
==> Installing dependencies for curl: pkg-config, openssl@1.1 and zlib
==> Installing curl dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/ligeng/.cache/Homebrew/downloads/5bdbf3b3fdadaf72744884b98b74a2ff887bd63a20b246f811a222a146ad7b64--pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/ligeng/.linuxbrew/Cellar/pkg-config/0.29.2_4 --disable-host-
Last 15 lines from /home/ligeng/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... powerpc64le-unknown-linux-gnu
checking host system type... powerpc64le-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20200424-145378-m2nvy3/pkg-config-0.29.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by runlevel5** [comment]
@Lyken17 could you please advise me the version of your gcc? I will try my best to fix it

**Comment by Lyken17** [comment]
Sure 

```bash
(base) [ligeng@service0001 ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
(base) [ligeng@service0001 ~]$ which gcc
/usr/bin/gcc
```

**Comment by runlevel5** [comment]
@Lyken17 Is it RHEL 7?

**Comment by Lyken17** [comment]
I think it is RHEL 7

```
(base) [ligeng@service0001 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

**Comment by runlevel5** [comment]
@Lyken17 I will set up that in VM and test it out myself

**Comment by runlevel5** [comment]
@Lyken17 I think I know why :D. The original homebrew does not support gcc 4.8 (ref: https://github.com/homebrew-ppc64le/brew/blob/master/Library/Homebrew/compilers.rb#L6). I will add support for gcc 4.8 tomorrow.

**Comment by runlevel5** [comment]
@Lyken17 let's move the discussion to the new issue I've just created https://github.com/homebrew-ppc64le/brew/issues/1
